### ISSUE TITLE
add option to set background color

### ISSUE THREAD

**Issue by edem-cyber** [javedmughal-058/fancy_onboarding_screen#1]

**Comment by javedmughal-058** [comment]
Hello Edem Agbakpe,

It's great to hear from you. I'm approving your request and will also publish the code on pub.dev. Thank you once again for taking the time to improve the code.

**Comment by javedmughal-058** [comment]
It's great to hear from you. I'm approving your request and will also publish the code on pub.dev. Thank you once again for taking the time to improve the code.
